### PR TITLE
Fix `verbose` for R bindings

### LINKED ISSUE #3675: [R] - `verbose` argument has no effect
#### Issue description

It seems that the `verbose` argument has no effect.

``` r
set.seed(1234)
x <- matrix(rnorm(10*5), ncol = 5)

# KNN EXAMPLE
res <- mlpack::knn(query = x, reference = x, k = 3, verbose = TRUE)

# expected :

[INFO ] 11 node combinations were scored.
[INFO ] 100 base cases were calculated.


# MST EXAMPLE
res3 <- mlpack::emst(x, verbose = TRUE)

# expected :

[INFO ] 6 edges found so far.
[INFO ] 90 cumulative base cases.
[INFO ] 1 cumulative node combinations scored.
[INFO ] 9 edges found so far.
[INFO ] 164 cumulative base cases.
[INFO ] 2 cumulative node combinations scored.
[INFO ] Total spanning tree length: 14.9797

packageVersion("mlpack")
[1] ‘4.3.0.1’

```

`verbose` argument doesn't assign its value in the list of parameters that is passed on to the binding algorithm; instead it invokes an R internal function, `EnableVerbose()` or `DisableVerbose()` which wraps the C++ helper EnableVerbose/DisableVerbose and these C++ helpers then simply call `Log::Info.ignoreInput = false or true`;

So, `Log::Info.ignoreInput` is invoked not within the binding function and as a result has no effect (at least this is my understanding).

cc: @coatless

### PR DESCRIPTION
**Pull request by rcurtin**
This fixes #3675.

I reproduced the issue and found that the `verbose` argument to mlpack's R bindings had no effect, even though the `EnableVerbose()` function was successfully being called.

This is because `Log::Info` (which is what the `EnableVerbose()` function modified) is a singleton object, and exists once *in each translation unit*.  Since `EnableVerbose()` is compiled into the translation unit for the file `r_util.cpp`, the `Log::Info` modified by `EnableVerbose()` ends up being *different* than the `Log::Info` that is being used by each individual binding---so, in essence, we are enabling verbose mode... with the wrong `Log::Info` object.

I fixed this by removing the standalone `EnableVerbose()` and `DisableVerbose()` functions, and instead modifying the `Log::Info` object's verbose state directly inside each printed binding.  So, e.g., this block is now gone from the R code:

```r
  if (verbose) {
    EnableVerbose()
  } else {
    DisableVerbose()
  }
```

and the actual binding code, which before looked like this:

```
// [[Rcpp::export]]
void knn_call(SEXP params, SEXP timers)
{
  util::Params& p = *Rcpp::as<Rcpp::XPtr<util::Params>>(params);
  util::Timers& t = *Rcpp::as<Rcpp::XPtr<util::Timers>>(timers);

  if (p.Has("verbose"))
    Log::Info.ignoreInput = false;
  else
    Log::Info.ignoreInput = true;

  BINDING_FUNCTION(p, t);
}
```

now looks like this:

```
// [[Rcpp::export]]
void knn_call(SEXP params, SEXP timers)
{
  util::Params& p = *Rcpp::as<Rcpp::XPtr<util::Params>>(params);
  util::Timers& t = *Rcpp::as<Rcpp::XPtr<util::Timers>>(timers);

  if (p.Has("verbose"))
    Log::Info.ignoreInput = false;
  else
    Log::Info.ignoreInput = true;

  BINDING_FUNCTION(p, t);
}
```

and so when I run the example code provided by @cgiachalis:

```r
set.seed(1234)
x <- matrix(rnorm(10*5), ncol = 5)

# KNN EXAMPLE
res <- mlpack::knn(query = x, reference = x, k = 3, verbose = TRUE)
```

I get this output instead of nothing:

```
> res <- mlpack::knn(query = x, reference = x, k = 3, verbose = TRUE)
[INFO ] Using reference data from 5x10 matrix.
[INFO ] Building reference tree...
[INFO ] Tree built.
[INFO ] Using query data from 5x10 matrix.
[INFO ] Searching for 3 neighbors with dual-tree kd-tree search...
[INFO ] 11 node combinations were scored.
[INFO ] 100 base cases were calculated.
[INFO ] 11 node combinations were scored.
[INFO ] 100 base cases were calculated.
[INFO ] Search complete.
```

Hooray!

### CODE REVIEW

File: src/mlpack/bindings/R/mlpack/src/rcpp_mlpack.h [hunk 1]
```diff
@@ -15,9 +15,6 @@
 
 #include <Rcpp.h>
 
-// To suppress Found '__assert_fail', possibly from 'assert' (C).
-#define BOOST_DISABLE_ASSERTS
```
Comment (rcurtin) [inline src/mlpack/bindings/R/mlpack/src/rcpp_mlpack.h:19]: @coatless @eddelbuettel @Yashwants19 if you don't mind sanity checking me on this one since I am not an R expert... I think it's no longer needed since we aren't using Boost.

Comment (eddelbuettel) [reply src/mlpack/bindings/R/mlpack/src/rcpp_mlpack.h:19]: Agreed, just remove.

**Comment by eddelbuettel** [comment]
That's a fine catch of the singleton issue.  I guess we could add a testthat predicate or two for silent vs verbose expectations?  (Not a big user of testthat myself but these test runners are all _roughly_ equivalent.)

**Comment by cgiachalis** [comment]
Thanks @rcurtin !

I just noticed that I forgot to mention a small suggestion in relation to verbose argument. It might be worth to add the ability to set the verbose state at the package level using `verbose =getOption(mlpack.verbose, default = FALSE)`.

Practically, if a user wants to use  verbose in all invocation s then using `options(mlpack.verbose=TRUE)` will do the job.

**Comment by eddelbuettel** [comment]
Good point.  And by using global state from R (as offered by R) you can also flip it on/off programmatically in subroutines.

**Comment by cgiachalis** [comment]
Yeap!

**Review by eddelbuettel — APPROVED** [review]
Approving now with _most_ but not all CI runs green.  The Azure stuff I will ignore :sunglasses:

File: src/mlpack/bindings/R/mlpack/src/rcpp_mlpack.h (hunk 1 above)
Comment (coatless) [reply src/mlpack/bindings/R/mlpack/src/rcpp_mlpack.h:19]: Yup, no longer needed with the shift away from boost!

**Review by coatless — APPROVED** [review]
LGTM. 

On the note of global options raised earlier, I would suggest adding that as a separate issue as it would involve modifications to how the function parameters are populated to get `getOption()` component, c.f.

https://github.com/mlpack/mlpack/blob/3e2a677704adcba6b989e06391c0eca4aaf9ef63/src/mlpack/bindings/R/print_R.cpp#L158
