### PR TITLE
Fix defeatist search for spill tree traversals

### LINKED ISSUE #1269: Nearest neighbors with spill trees in dualtree mode does not always return neighbors
I have noticed that if the k is big the dual tree algorithm will return max float distances and invalid indices. This probably happens because some leaf nodes do not have enough points

### PR DESCRIPTION
**Pull request by rcurtin**
This fixes #1269 (@vasiloglou can finally rejoice).  The problem is detailed in that issue, but in short, it is possible to construct a spill tree in such a way that during a defeatist traversal *not enough* base cases are computed, and this can lead to an issue where, e.g., nearest neighbor search does not return enough results.  (A defeatist traversal is, basically, a depth-first traversal with no backtracking.)

The strategy that I have used to counter this problem is to add a `MinimumBaseCases()` function to each `Rules` class, and then during traversal, catch when we have recursed "too far" during a defeatist traversal and the reference node has fewer than `MinimumBaseCases()` descendant points.  When that happens, we just go back up one level and brute-force perform `BaseCase()` on all descendant points.  This then guarantees that we will get the right number of results.  There is a little bit of complexity in the condition to catch this, because the spill tree traverser only *sometimes* takes defeatist steps during recursion.

I've also added a test case to make sure this behavior functions properly.

Interestingly, the `GreedySingleTreeTraverser` in `src/mlpack/core/tree/greedy_single_tree_traverser.hpp` already accounts for this situation---but the `SpillTree` does not use that traverser.  I refactored `GreedySingleTreeTraverser` to also use `MinimumBaseCases()`.

### CODE REVIEW

**Comment by rcurtin** [comment]
Oh, I'm lucky that the build failed!  There is actually a subtle bug here.  I will have to think about the right way to fix it.  I at least managed to isolate it tonight.

**Comment by rcurtin** [comment]
Alright, looks like everything is fixed here.  I also ran the tests for several hundred iterations locally to make sure there was no problem.

File: src/mlpack/core/tree/spill_tree/spill_dual_tree_traverser_impl.hpp [hunk 1]
```diff
@@ -50,23 +50,39 @@ SpillDualTreeTraverser<RuleType, Defeatist>::Traverse(
...
+  // Determine whether we need to brute-force the reference node.  We have no
+  // realistic way to track how many base cases we've done for each point, so we
+  // act as though we have done zero.
+  if (!bruteForce && Defeatist &&
+      (referenceNode.Parent() != NULL) &&
+      (referenceNode.Parent()->Overlap()) &&
+      (referenceNode.NumDescendants() < rule.MinimumBaseCases()))
   {
+    // We've actually recursed too far.  Go back up one level and brute-force
+    // the computation, and then we are done.
```
Comment (zoq) [inline src/mlpack/core/tree/spill_tree/spill_dual_tree_traverser_impl.hpp:71]: I really like the comments.

File: src/mlpack/core/tree/spill_tree/spill_tree.hpp [hunk 2]
```diff
@@ -90,8 +90,8 @@ class SpillTree
   //! The number of points of the dataset contained in this node (and its
   //! children).
   size_t count;
-  //! The list of indexes of points contained in this node (non-null for
-  //! leaf nodes).
+  //! The list of indexes of points contained in this node (non-NULL if the node
```
Comment (zoq) [inline src/mlpack/core/tree/spill_tree/spill_tree.hpp:93]: Interesting, "index" is one of those rare words that have two different plurals in English, didn't know that.

File: src/mlpack/tests/knn_test.cpp [hunk 3]
```diff
@@ -1766,7 +1766,51 @@ TEST_CASE("KNNGreedyTreeSearch", "[KNNTest]")
...
+/**
+ * Check that no garbage value is returned when greedy tree traversal
+ * is performed over spill trees.
+ */
+TEST_CASE("KNNSpillTreeSearchEnoughResults", "[KNNTest]")
+{
+  // Initalize dataset.
+  arma::mat dataset = arma::randu<arma::mat>(3, 100);
+
+  // Build tree with a leaf_size of 1.
```
Comment (zoq) [inline src/mlpack/tests/knn_test.cpp:1783]: leaf_size, hm, should this be "leaf size", since this is no main test?

File: src/mlpack/tests/main.cpp [hunk 4]
```diff
@@ -22,8 +22,8 @@ int main(int argc, char** argv)
    * each run.  This is good for ensuring that a test's tolerance is sufficient
    * across many different runs.
    */
-  // size_t seed = std::time(NULL);
-  // math::RandomSeed(seed);
+   // size_t seed = std::time(NULL);
+   // mlpack::math::RandomSeed(seed);
```
Comment (zoq) [inline src/mlpack/tests/main.cpp:26]: I think this was correctly formatted before?

Comment (rcurtin) [reply src/mlpack/tests/main.cpp:26]: You're right!  Not sure how I missed that.  Fixed in 41756e656.

File: src/mlpack/tests/knn_test.cpp (hunk 3 above)
Comment (rcurtin) [reply src/mlpack/tests/knn_test.cpp:1783]: Good point---fixed in 9fb1d3de2.

File: src/mlpack/core/tree/spill_tree/spill_tree.hpp (hunk 2 above)
Comment (rcurtin) [reply src/mlpack/core/tree/spill_tree/spill_tree.hpp:93]: Yeah, it's sometimes hard to know which one to use. :smile:

**Review by zoq — APPROVED** [review]
Looks great to me.
