### PR TITLE
Remove ElemType template parameter from DecisionTree

### LINKED ISSUE #2872: Should ClassProbabilities be ElemType?
### Why the classProbabilities defined in functions of class AllCategoricalSplit/BestBinaryNumericSplit is arma::Col\<ElemType\>?
When I want to pass a inputData of type arma::Mat\<int\> to DecisionTree, there will be a no matching funtion error, so that I find the key may be the classProbabilities.
Because the definition of classProbabilities is done by code "classProbabilities(numClasses)", the func NumChildren in BestBinaryNumericSplit or CalculateDirection in AllCategoricalSplit is required for a classProbabilities of type arma::Col\<ElemType\>. The ElemType is the same as the template of inputData. But I think the type of probabilitiy should always be double.
Is it necessary to rule the template of accessing classProbabilities be ElemType?
I'm new for C++. If my thought is wrong, I require for a way to pass int mat as inputData to train a DecisionTree!

```cpp
#include <mlpack/core.hpp>
#include <mlpack/methods/adaboost/adaboost.hpp>
#include <mlpack/methods/decision_tree/multiple_random_dimension_select.hpp>
#include <armadillo>
#include <chrono>

using namespace std;
using namespace chrono;
using namespace arma;
using namespace mlpack;
using namespace data;
using namespace mlpack::adaboost;
using namespace mlpack::tree;
using namespace mlpack::perceptron;

int main() {
    freopen("../out", "w+", stdout);
    cout << "hello" << endl;
    Mat<int> inputData;
    data::Load("../num.csv", inputData);
    arma::Row<size_t> labels;
    data::Load("../label.csv", labels);
    const size_t numClasses = max(labels.row(0)) + 1;
    // Define your own weak learner, perceptron in this case.
    // Run the perceptron for perceptronIter iterations.
//    int perceptronIter = 400;
//    Perceptron<> p(inputData, labels.row(0), numClasses, perceptronIter);
    for (int ls = 1; ls <= 1; ls++) {
        for (int d = 1; d <= 1; d++) {
            for (int it = 1; it <= 1; it++) {
                for (int dim = 1; dim <= 1; dim++) {
                    cout << "------" << "ls=" << ls << ";d=" << d << ";it=" << it << ";dim=" << dim << endl;
                    DecisionTree<
                            InformationGain,
                            BestBinaryNumericSplit,
                            AllCategoricalSplit,
                            AllDimensionSelect,
                            int,
                            false> t(
                            inputData,
                            labels,
                            numClasses,
                            ls,
                            1e-30,
                            d
                    );
                    // Define parameters for AdaBoost.
                    size_t iterations = it;
                    double tolerance = 1e-8;
                    AdaBoost<
                            DecisionTree<
                                    InformationGain,
                                    BestBinaryNumericSplit,
                                    AllCategoricalSplit,
                                    AllDimensionSelect,
                                    int,
                                    false>, arma::Mat<int>> a(tolerance);
                    auto start = system_clock::now();
                    a.Train(inputData, labels.row(0), numClasses, t,
                            iterations, tolerance);
                    auto end = system_clock::now();
                    auto duration = duration_cast<microseconds>(end - start);
                    cout << "Train Spent: "
                         << double(duration.count()) * microseconds::period::num / microseconds::period::den
                         << " seconds."
                         << endl;
                    arma::Row<size_t> predictedLabels;
                    start = system_clock::now();
                    for (int i = 0; i < 5; i++)
                        a.Classify(inputData, predictedLabels);
                    cout << "Number: " << a.WeakLearners() << endl;
                    end = system_clock::now();
                    duration = duration_cast<microseconds>(end - start);
                    cout << "Test Spent: "
                         << double(duration.count()) * microseconds::period::num / microseconds::period::den
                         << " seconds."
                         << endl;
                    size_t countError = arma::accu(labels != predictedLabels);
                    double hammingLoss = (double) countError / labels.n_cols;
                    cout << "Error Number: " << countError << endl;
                    Save("trial.xml", "model", a, false);
                    AdaBoost<
                            DecisionTree<
                                    InformationGain,
                                    BestBinaryNumericSplit,
                                    AllCategoricalSplit,
                                    AllDimensionSelect,
                                    int,
                                    false>, arma::Mat<int>> b;
                    Load("trial.xml", "model", b);
                    for (int i = 0; i < 5; i++)
                        b.Classify(inputData, predictedLabels);
                for (int i = 0; i < 10000; i++) {
                    assert(predictedLabels.at(i) == labels.at(i));
                }
                }
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by rcurtin**
While fixing #2872, I noticed that there is a template parameter `ElemType` for `DecisionTree` and `RandomForest` that is currently entirely unused.  In fact, it gets in the way and is confusing a little bit, so I thought it was better to remove it.

In addition, I changed some function signatures to force `arma::vec` for the `classProbabilities` member to actually fix #2872.

This is an API change, but since the next release is 4.0.0 anyway, it should be okay to break reverse compatibility in this minor way.

### CODE REVIEW

File: src/mlpack/tests/decision_tree_test.cpp [hunk 1]
```diff
@@ -701,6 +701,66 @@ TEST_CASE("SimpleGeneralizationTest", "[DecisionTreeTest]")
...
+  // Figure out the accuracy.
+  double correct = 0.0;
+  for (size_t i = 0; i < predictions.n_elem; ++i)
+    if (predictions[i] == trueTestLabels[i])
+      ++correct;
+  correct /= predictions.n_elem;
+
+  REQUIRE(correct > 0.75);
+
+  // reset the prediction
```
Comment (zoq) [inline src/mlpack/tests/decision_tree_test.cpp:748]:
```suggestion
  // Reset the prediction.
```

File: src/mlpack/tests/decision_tree_test.cpp [hunk 2]
```diff
@@ -701,6 +701,66 @@ TEST_CASE("SimpleGeneralizationTest", "[DecisionTreeTest]")
...
+  arma::Row<size_t> labels;
+  if (!data::Load("vc2_labels.txt", labels))
+    FAIL("Cannot load labels for vc2_labels.txt");
+
+  // Initialize an all-ones weight matrix.
+  arma::rowvec weights(labels.n_cols, arma::fill::ones);
+
+  // Build decision tree.
+  DecisionTree<> d(inputData, labels, 3, 10); // Leaf size of 10.
+  DecisionTree<> wd(inputData, labels, 3, weights, 10); // Leaf size of 10.
```
Comment (zoq) [inline src/mlpack/tests/decision_tree_test.cpp:722]:
```suggestion
  DecisionTree<> d(inputData, labels, 3, 10 /* Leaf size of 10. */);
  DecisionTree<> wd(inputData, labels, 3, weights, 10 /* Leaf size of 10. */);
```

Wondering if attaching the comment to the parameter makes it more clear?

Comment (rcurtin) [reply src/mlpack/tests/decision_tree_test.cpp:722]: Ah, nice, agreed. :+1:

**Review by zoq — APPROVED** [review]
Looks great to me.

**Review by birm — APPROVED** [review]
Are you looking to push this change with 4.0.0, or now?

**Comment by rcurtin** [comment]
We've already done the last 3.x release, since we've made a bunch of not-reverse-compatible changes, so let's go ahead and merge it now. :+1:
