### PR TITLE
Rectified Predict() in rnn_impl (#1846).

### LINKED ISSUE #1846: RNN: Fails to run Predict() if called before Train().
#### Issue description
```c++
  const size_t rho = 5;
  arma::cube questions = arma::ones(1,2,rho);
  arma::cube answers = arma::ones(1,2,rho);
  
  mlpack::ann::RNN<mlpack::ann::MeanSquaredError<> > model(rho);
  model.Add<mlpack::ann::Linear<> >(1, 10);
  model.Add<mlpack::ann::LSTM<> >(10,10);
  model.Add<mlpack::ann::Linear<> >(10, 1);
  
  model.Parameters().randu();
  model.Predict(questions, answers);
```
Running the above snippet produces :
```bash
error: Mat::submat(): indices out of bounds or incorrectly used
  terminate called after throwing an instance of 'std::logic_error'
    what():  Mat::submat(): indices out of bounds or incorrectly used
  Aborted (core dumped)
```
However, if the last line in the above snippet is replaced by:
```c++
model.Train(questions, answers);
model.Predict(questions, answers);
```
It works perfectly. 
#### Steps to reproduce

Running the [code](https://pastebin.com/LNafNMUu).

#### Expected behaviour

RNN class methods Predict() and Train() (actually Evalute()) should be consistent.

#### Actual behavior

Fails to run Predict() if called before Train()/ Evaluate().

### PR DESCRIPTION
**Pull request by MuLx10**
```c++
  const size_t rho = 5;
  arma::cube questions = arma::ones(1,2,rho);
  arma::cube answers = arma::ones(1,2,rho);
  
  mlpack::ann::RNN<mlpack::ann::MeanSquaredError<> > model(rho);
  model.Add<mlpack::ann::Linear<> >(1, 10);
  model.Add<mlpack::ann::LSTM<> >(10,10);
  model.Add<mlpack::ann::Linear<> >(10, 1);
  
  model.Parameters().randu();
  model.Predict(questions, answers);
```
Running the above snippet produces :
```bash
error: Mat::submat(): indices out of bounds or incorrectly used
  terminate called after throwing an instance of 'std::logic_error'
    what():  Mat::submat(): indices out of bounds or incorrectly used
  Aborted (core dumped)
```
However, if the last line in the above snippet is replaced by:
```c++
model.Train(questions, answers);
model.Predict(questions, answers);
```
It works perfectly. 
Evalute method sets RNN::outputSize. When predict is called before Train() RNN::outputSize is 0. 
Thus Mat::submat() fails.This PR makes Predict and Evaluate method of class RNN consistent by adding a test and set for RNN::outputSize .
Closes #1846 .

### CODE REVIEW

File: src/mlpack/methods/ann/rnn_impl.hpp [hunk 1]
```diff
@@ -164,9 +164,16 @@ void RNN<OutputLayerType, InitializationRuleType, CustomLayers...>::Predict(
...
           predictors.n_rows, effectiveBatchSize, false, true)));
 
-      results.slice(seqNum).submat(0, begin, results.n_rows - 1, begin +
-          effectiveBatchSize - 1) = boost::apply_visitor(outputParameterVisitor,
+      arma::mat out = boost::apply_visitor(outputParameterVisitor,
           network.back());
+
+      if (results.n_rows == 0)
+      {
+        results.set_size(out.n_rows, predictors.n_cols, rho);
```
Comment (saksham189) [inline src/mlpack/methods/ann/rnn_impl.hpp]: I am not in strong favour of this change. We already check and set `outputSize` inside `EvaluateWithGradient` and `Evaluate` methods and adding it inside `Predict` makes it redundant in the code + it is inefficient to have it within 2 for loops here. 
Rather I think we could set `outputSize` once inside the `ResetParameters()` method by creating a `OutputSizeVisitor` and reverse iterating over the layers until we have a non-zero value. This way we can remove the need to check `outputSize == 0` inside every method.
I think we are doing something similar here https://github.com/mlpack/mlpack/pull/1366 which has an implementation of the `outputSizeVisitor`.
Let me know what you think. @MuLx10 @zoq

Comment (MuLx10) [reply src/mlpack/methods/ann/rnn_impl.hpp]: @saksham189 I agree that checking redundant conditions within two loops is very inefficient. I will rectify that. However, I am not sure that I should remove that from other functions like Evaluate().  @zoq I would like to have your views.

Comment (zoq) [reply src/mlpack/methods/ann/rnn_impl.hpp]: Sounds like a good idea to me, @MuLx10 feel free to remove the part from the other functions as well.

Comment (MuLx10) [reply src/mlpack/methods/ann/rnn_impl.hpp]: okay sure

**Comment by zoq** [comment]
@MuLx10 Let me know if I should take a look into the build issue.

**Comment by MuLx10** [comment]
@zoq I figured out the problem. However, I am having  difficulty finding the solution

**Comment by zoq** [comment]
Happy to help, perhaps you can pinpoint me to the issue?

File: src/mlpack/methods/ann/rnn_impl.hpp [hunk 2]
```diff
@@ -153,6 +153,12 @@ void RNN<OutputLayerType, InitializationRuleType, CustomLayers...>::Predict(
     ResetDeterministic();
   }
 
+  arma::mat resultsTemp;
+  Forward(std::move(arma::mat(predictors.slice(0).colptr(0),
```
Comment (zoq) [inline src/mlpack/methods/ann/rnn_impl.hpp]: What about we move this into the for loop and set the site of `result` at the first step?

Comment (MuLx10) [reply src/mlpack/methods/ann/rnn_impl.hpp]: @zoq  that's what I did in the [previous commit](https://github.com/mlpack/mlpack/pull/1847/commits/dc3cbf46d95e9a940c6a4510f6ff45e4e54c63c7).

Comment (zoq) [reply src/mlpack/methods/ann/rnn_impl.hpp]: Ahh, right, I think in this case it's faster to check this at the first step once, instead of doing a complete forward pass; or what about we start with ``begin = 1`` (do the first step outside of the for loop). Let me know what you think.

Comment (MuLx10) [reply src/mlpack/methods/ann/rnn_impl.hpp]: Yes, that might work. Thanks @zoq

**Comment by MuLx10** [comment]
@mlpack-jenkins

**Comment by saksham189** [comment]
Thanks for fixing this @MuLx10 . I got a bit busy with exams. This looks good to me. I will try and implement my idea in a separate PR.

**Comment by zoq** [comment]
Thanks again for the contribution.

**Comment by MuLx10** [comment]
@saksham189 Yeah sure. @zoq Thanks.
