### PR TITLE
fix default output problem and some styles

### LINKED ISSUE #667: mlpack_preprocess_split doesn't work when absolute paths are specified
Here's what I tried to do to play with it:

```
$ bin/mlpack_preprocess_split -i ~/datasets/corel.csv -I ~/datasets/corel.csv -t corel-train.csv -T corel-test.csv -v
[DEBUG] Compiled with debugging symbols.
[WARN ] You did not specify --training_labels_file, so the trainingset labels file name will be automatically set to 'train_/home/ryan/datasets/corel.csv'.
[WARN ] You did not specify --test_labels_file, so the test set labels file name will be automatically set to 'test_/home/ryan/datasets/corel.csv'.
[WARN ] You did not specify --test_ratio, so it will be automatically set to 0.2.
[INFO ] Loading '/home/ryan/datasets/corel.csv' as CSV data.  Size is 32 x 37749.
[INFO ] Loading '/home/ryan/datasets/corel.csv' as CSV data.  Size is 32 x 37749.
[INFO ] Training data contains 30200 points.
[INFO ] Test data contains 7549 points.
[INFO ] Saving CSV data to 'corel-train.csv'.
[INFO ] Saving CSV data to 'corel-test.csv'.
[WARN ] Cannot open file 'train_/home/ryan/datasets/corel.csv' for writing; save failed.
[WARN ] Cannot open file 'test_/home/ryan/datasets/corel.csv' for writing; save failed.
[INFO ] 
[INFO ] Execution parameters:
[INFO ]   help: false
[INFO ]   info: ""
[INFO ]   input_file: /home/ryan/datasets/corel.csv
[INFO ]   input_labels_file: /home/ryan/datasets/corel.csv
[INFO ]   test_file: corel-test.csv
[INFO ]   test_labels_file: ""
[INFO ]   test_ratio: 0.2
[INFO ]   training_file: corel-train.csv
[INFO ]   training_labels_file: ""
[INFO ]   verbose: true
[INFO ]   version: false
[INFO ] 
[INFO ] Program timers:
[INFO ]   loading_data: 1.012701s
[INFO ]   saving_data: 0.530123s
[INFO ]   total_time: 1.631944s
```

So I guess, we need to be more careful with prepending "train_", we have to do it in the right place.  Maybe some string tokenization is necessary. :(

Also, Keon, I made a few formatting and documentation changes in 6a94eb6, please let me know if I broke anything.

### PR DESCRIPTION
**Pull request by keonkim**
add duplicate option identifier/alias check (issue #671)
fix default output filename problem stated in #667 
and unified some styles
- variable.empty() -> CLI::HasParam("variable")
- for small executables, initialize specified parameters as consts. All at the beginning of the prorgram.
- changed unclear initialized variables to camel case of the original parameter (ex, output_probabilities_file -> outputProbabilitiesFile)
- unified name of the parameters (ex, probabilities_file -> output_probabilities_file; predictions_file -> output_predictions_file)

drop following unused functions inside util
* SanitizeString
* ParseStream

### CODE REVIEW

**Comment by stereomatchingkiss** [comment]
@keonkim Please wait a moment, I will study your codes on this Thursday

File: src/mlpack/core/util/cli_impl.hpp [hunk 1]
```diff
@@ -28,39 +38,53 @@ namespace mlpack {
...
+  gmap_t& gmap = GetSingleton().globalValues;
+  amap_t& amap = GetSingleton().aliasValues;
+
+  // if found in current map, print fatal error and terminat program.
+  if (gmap.count(identifier))
+    outstr << "Parameter --" << identifier << "(-" << alias << ") "
+           << "is defined multiple times with same identifiers." << std::endl;
+  if (amap.count(alias))
+    outstr << "Parameter --" << identifier << "(-" << alias << ") "
+           << "is defined multiple times with same alias." << std::endl;
```
Comment (rcurtin) [inline src/mlpack/core/util/cli_impl.hpp]: This is a good way to solve the problem of duplicate options, I like it.

File: src/mlpack/methods/emst/emst_main.cpp [hunk 2]
```diff
@@ -34,8 +34,8 @@ PROGRAM_INFO("Fast Euclidean Minimum Spanning Tree", "This program can compute "
     "column corresponds to the distance between the two points.");
 
 PARAM_STRING_REQ("input_file", "Data input file.", "i");
-PARAM_STRING("output_file", "Data output file.  Stored as an edge list.", "o",
-    "emst_output.csv");
+PARAM_STRING_REQ("output_file", "Data output file.  Stored as an edge list.",
+    "o");
```
Comment (rcurtin) [inline src/mlpack/methods/emst/emst_main.cpp]: We shouldn't require the user to specify and output file, but we should print a warning ("output will not be saved", I think mlpack_knn does this) if they don't specify -o.

File: src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp [hunk 3]
```diff
@@ -56,10 +56,10 @@ PARAM_STRING("output_model_file", "File to save trained tree to.", "M", "");
...
 PARAM_STRING("test_file", "File of testing data.", "T", "");
 PARAM_STRING("test_labels_file", "Labels of test data.", "L", "");
-PARAM_STRING("predictions_file", "File to output label predictions for test "
-    "data into.", "p", "");
-PARAM_STRING("probabilities_file", "In addition to predicting labels, provide "
-    "prediction probabilities in this file.", "P", "");
+PARAM_STRING("output_predictions_file", "File to output label predictions for"
+    "test data into.", "p", "");
+PARAM_STRING("output_probabilities_file", "In addition to predicting labels, "
+    "provide prediction probabilities in this file.", "P", "");
```
Comment (rcurtin) [inline src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp]: Do you think that changing this parameter name violates our versioning policy for minor release changes?  I think I consider this a "public" part of the program, so I don't think we should change it until the next major release (3.0.0, I don't know when that will be), but I could probably be convinced either way.

File: src/mlpack/methods/emst/emst_main.cpp (hunk 2 above)
Comment (keonkim) [inline src/mlpack/methods/emst/emst_main.cpp]: @rcurtin I also applied same changes to other files in the following commit

File: src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp (hunk 3 above)
Comment (keonkim) [inline src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp]: Hmm.. since this is a command line executable, I think it wouldn't create problems with the downstream applications. But I think it is indeed a public part, should I wait til 3.0.0?

**Comment by stereomatchingkiss** [comment]
The codes looks good for me, it is nice to see the codes become easier to read and more consistent. If possible, could you split the pull request into two parts next time?Like "fix default output problem" and "fix some styles" rather than put them altogether.

File: src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp (hunk 3 above)
Comment (keonkim) [inline src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp]: @rcurtin: hmm, as I think of it now, I don't think it is a public "API" that downstream apps make use of.

**Comment by keonkim** [comment]
@stereomatchingkiss thanks for the comment!
I will split into major chunks next time, sorry about that.

File: src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp (hunk 3 above)
Comment (rcurtin) [inline src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp]: I'm not sure, I could consider the command line executables and their options to be part of the public API. @zoq, @stereomatchingkiss, any thoughts on this one? If both of you agree that we don't violate our versioning policy here I think it is fine to make the change, otherwise maybe we should wait (or provide reverse compatibility options).

Comment (zoq) [inline src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp]: I agree with @rcurtin this is definitely part of the public API. I would agree on an exception if the change fixes a bug or something like that, but I don't think that's the case here.

Comment (stereomatchingkiss) [inline src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp]: I agree with @rcurtin too, we could make the changes of CLI parameters name at next major release.

**Comment by stereomatchingkiss** [comment]
@keonkim Don't mind :)

File: src/mlpack/methods/softmax_regression/softmax_regression_main.cpp [hunk 4]
```diff
@@ -21,9 +21,9 @@ PROGRAM_INFO("Softmax Regression", "This program performs softmax regression, "
     "(-r), and if an intercept term is not desired in the model, the "
     "--no_intercept (-N) can be specified."
     "\n\n"
-    "The trained model can be saved to a file with the --output_model (-m) "
+    "The trained model can be saved to a file with the --output_model_file (-m) "
     "option.  If training is not desired, but only testing is, a model can be "
-    "loaded with the --input_model (-i) option.  At the current time, a loaded "
+    "loaded with the --input_model_file (-i) option.  At the current time, a loaded "
```
Comment (keonkim) [inline src/mlpack/methods/softmax_regression/softmax_regression_main.cpp]: actually for this one, it declares "input_model_file" as PARAM but uses "input_model" in the main function and documentation. So I changed everything to "input_model_file".

File: src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp (hunk 3 above)
Comment (keonkim) [inline src/mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp]: I changed them back to follow the policy :)

File: src/mlpack/methods/hmm/hmm_viterbi_main.cpp [hunk 5]
```diff
@@ -72,6 +73,10 @@ int main(int argc, char** argv)
   // Parse command line options.
   CLI::ParseCommandLine(argc, argv);
 
+  if (CLI::HasParam("output_file"))
+    Log::Warn << "--output_file (-o) is not specified;"
+      << "no results will be saved!" << endl;
```
Comment (rcurtin) [inline src/mlpack/methods/hmm/hmm_viterbi_main.cpp]: Could you reformat this a little bit please? (There are lots of messages like this so my comment applies to all of them, not just this one.)  More of the message might fit on one line, and when you wrap, be sure to have two extra indents before the `<< "rest of the message." << endl` part.

**Comment by rcurtin** [comment]
Looks good to me, thank you very much for taking the time to do this!  :)

File: .gitignore [hunk 6]
```diff
@@ -6,3 +6,6 @@ build*
 *.bak
 src/mlpack/core/util/gitversion.hpp
 src/mlpack/core/util/arma_config.hpp
+
+.idea
```
Comment (zoq) [inline .gitignore]: You can also create or modify the global ``~/.gitignore`` file or any other file:

``
git config --global core.excludesfile '~/.gitignore'
``

File: src/mlpack/methods/hmm/hmm_viterbi_main.cpp (hunk 5 above)
Comment (keonkim) [inline src/mlpack/methods/hmm/hmm_viterbi_main.cpp]: @rcurtin I updated it :)

File: .gitignore (hunk 6 above)
Comment (keonkim) [inline .gitignore]: @zoq Do you think it is better to leave this configuration in my local machine?

Comment (zoq) [inline .gitignore]: I would say so, yes. What program generates a .idea file?

Comment (rcurtin) [inline .gitignore]: Ok, I'll remove both .idea and other editor-specific swap files from .gitignore then.

Comment (keonkim) [inline .gitignore]: I tried coding with [Clion IDE](https://www.jetbrains.com/clion/).
Seems like Jetbrain IDEs all create .idea files. I will roll this back in the next pull request :)

Comment (rcurtin) [inline .gitignore]: No need, I already rolled it back in a8b5be9.  I also made a few simple style changes in c6477da.
