### PR TITLE
Fix cover tree issues by @rcurtin fixes #2869

### LINKED ISSUE #2869: Some of mlpack tests are failing on aarch64 machines
Hello everyone,

Following the work on this pull request #2531, we have noticed recently that there are several mlpack tests that are failing when executed on aarch64 architecture (arm architecture 64 bits). These tests are related to:

* FastMKSTest: Failing
* AKFNTest: Failing
* AKNNTest: Failing
* KFNTest: Failing
* KNNTest: Failing
* KMeansTest: Failing (DTNNCoverTreeTest) precisely
* KDETest: Failing (StandardCoverTreeGaussianTest)
* RangeSearchTest: Failing (RSCoverTreeTest)
* EmstTest: Failing (EmstCoverTreeTest)
* KMeansMainTest: Failing (AlgorithmSimilarTest)
* KDEMainTest: Failing (KDEMonoResultMain)

Note that, not all the tests inside these tags are failing, but some of them (Those related to dual cover tree). After running these failing tests, you should expect to enter an infinite loop that never ends. Finally, you will have to use Ctrl-C to stop it.

Usually, we cross-compile binaries from x86_64 bit machines to aarch64 machines, however lately I have found that 
the same issue is produced even though if I compiled these binaries locally on aarch64 (depending on which test you are executing)

I have tested several tests, the following tests (I thought they were relevant) are passing without any issue:
* TreeTest: Passing
* RectangleTreeTraitsTest: Passing
* KernelTest: Passing
* CosineTreeTest: Passing
* KRANNTest: Passing
* HoeffdingTreeTest: Passing
* SerializationTest: Passing
* TreeTraitsTest: Passing
* UBTreeTest: Passing
* VanatagePointTreeTest: Passing

If you have any test to execute that you think might be relevant to this issue, please let me know, and I will add the results back here. To reproduce the issue you need to have access to aarch64 machine through qemu emulator or physical hardware, if you have an idea and you would like to try, but you do not have access to the machine, please leave in a comment and a piece of code to add, modify or to examine and I will be very happy to the tests.

#### Here are some details about the test environment
 * Raspberry Pi 3 with ubuntu 20. (Zin64 on Jenkins)
 * Viking machine on Jenkins
 * version of mlpack: The master version
 * operating system: arch Linux, ubuntu
 * cross-compiler: the mainstream gcc 10 cases more of this issue, I am using this version of buildroot [https://toolchains.bootlin.com/](cross-compilers)
 * compiler: the mainstream version of gcc that you can find in any aarch64

#### Interesting info:
Try to use the buildroot cross-compiler set, since it is the only one that produced binaries that were having the same failure as the local compiler for an aarch64. However, if you use the main gcc cross-compiler. I think it should be fine.  

#### Steps to reproduce
Cross-compile mlpack tests for aarch64 or locally build these tests from aarch64 machine.
`./bin/mlpack_test  [FastMKSTest]`

PS: I will update the issue regularly with any tests that are passing that are using the cover tree

### PR DESCRIPTION
**Pull request by shrit**
This pull request closes #2869 and fixes all errors from cover tree
when trying to put mlpack on arm64 devices.
Thanks to @rcurtin to put all effort to resolve this one.

Authored-by: Ryan Curtin <ryan@ratml.org>
Signed-off-by: Omar Shrit <omar@shrit.me>

### CODE REVIEW

File: src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp [hunk 1]
```diff
@@ -87,19 +87,23 @@ class CoverTree<MetricType, StatisticType, MatType, RootPointPolicy>::
...
+                std::map<int,
+                         std::vector<DualCoverTreeMapEntry>,
+                         std::greater<int>>& childMap);
 
   void ReferenceRecursion(CoverTree& queryNode,
-                          std::map<int, std::vector<DualCoverTreeMapEntry> >&
-                              referenceMap);
+                          std::map<int,
+                                   std::vector<DualCoverTreeMapEntry>,
+                                   std::greater<int>>& referenceMap);
```
Comment (zoq) [inline src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp:106]: I guess, at some places we are not really consistent with the indentation, because sometimes the parameter aligns with the first line, sometimes it's tabbed twice. For example `dual_tree_traverser_impl.hpp` uses the tabbed twice style, which is what the style guide recommends, so to be consistent let's adapt the style here?

Comment (shrit) [reply src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp:106]: I will fix the indentation. :+1:

File: src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp [hunk 2]
```diff
@@ -87,19 +87,23 @@ class CoverTree<MetricType, StatisticType, MatType, RootPointPolicy>::
    * Helper function for traversal of the two trees.
    */
   void Traverse(CoverTree& queryNode,
```
Comment (rcurtin) [inline src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp:89]:
```suggestion
  void Traverse(
      CoverTree& queryNode,
```

File: src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp [hunk 3]
```diff
@@ -87,19 +87,23 @@ class CoverTree<MetricType, StatisticType, MatType, RootPointPolicy>::
...
-                std::map<int, std::vector<DualCoverTreeMapEntry> >&
-                    referenceMap);
+                std::map<int,
+                         std::vector<DualCoverTreeMapEntry>,
+                         std::greater<int>>& referenceMap);
```
Comment (rcurtin) [inline src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp:92]:
```suggestion
      std::map<int, std::vector<DualCoverTreeMapEntry>,
          std::greater<int>>& referenceMap);
```
This one is a bit tough; the std::map type is really long.  But maybe this is better?

File: src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp [hunk 4]
```diff
@@ -87,19 +87,23 @@ class CoverTree<MetricType, StatisticType, MatType, RootPointPolicy>::
...
 
   //! Prepare map for recursion.
   void PruneMap(CoverTree& queryNode,
```
Comment (rcurtin) [inline src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp:95]:
```suggestion
  void PruneMap(
      CoverTree& queryNode,
```

File: src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp [hunk 5]
```diff
@@ -87,19 +87,23 @@ class CoverTree<MetricType, StatisticType, MatType, RootPointPolicy>::
...
-                std::map<int, std::vector<DualCoverTreeMapEntry> >&
-                    referenceMap,
-                std::map<int, std::vector<DualCoverTreeMapEntry> >&
-                    childMap);
+                std::map<int,
+                         std::vector<DualCoverTreeMapEntry>,
+                         std::greater<int>>& referenceMap,
+                std::map<int,
+                         std::vector<DualCoverTreeMapEntry>,
+                         std::greater<int>>& childMap);
```
Comment (rcurtin) [inline src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp:101]:
```suggestion
      std::map<int, std::vector<DualCoverTreeMapEntry>,
          std::greater<int>>& referenceMap,
      std::map<int, std::vector<DualCoverTreeMapEntry>,
          std::greater<int>>& childMap);
```

File: src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp [hunk 6]
```diff
@@ -87,19 +87,23 @@ class CoverTree<MetricType, StatisticType, MatType, RootPointPolicy>::
...
 
   void ReferenceRecursion(CoverTree& queryNode,
```
Comment (rcurtin) [inline src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp:103]:
```suggestion
  void ReferenceRecursion(
      CoverTree& queryNode,
```

File: src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp (hunk 1 above)
Comment (rcurtin) [inline src/mlpack/core/tree/cover_tree/dual_tree_traverser.hpp:106]:
```suggestion
    std::map<int, std::vector<DualCoverTreeMapEntry>,
        std::greater<int>>& referenceMap);
```

**Review by rcurtin — COMMENTED** [review]
Here's an attempt at style improvement; let me know what you think. :+1:

**Comment by shrit** [comment]
It is good from my side, @zoq any thoughts

**Comment by zoq** [comment]
> It is good from my side, @zoq any thoughts ?

Thanks looks good, I guess I'm somewhat pedantic when it comes to the style.

**Review by zoq — APPROVED** [review]
Really interesting issue that was fixed here, I encourage everyone to read the comments in #2869.

**Comment by rcurtin** [comment]
> > It is good from my side, @zoq any thoughts ?
> 
> Thanks looks good, I guess I'm somewhat pedantic when it comes to the style.

I think the pedantry is good; it helps keep the code consistent and reduces maintenance burden later (at least in my opinion :smile:).
