### PR TITLE
Column-major responses in Linear Regression and LARS

### LINKED ISSUE #963: Regarding Linear Regression and LARS
As of now linear regression has constructor : 
`LinearRegression::LinearRegression(`
`const arma::mat& predictors,`
   `                                                       const arma::vec& responses,`
`                                                       const double lambda,`
`                                                       const bool intercept,`
`                                                       const arma::vec& weights)`
And training method as : 
` LinearRegression::Train(`
`const arma::mat& predictors,`
`                                     const arma::vec& responses,`
`                                     const bool intercept,`
`                                     const arma::vec& weights)`

And LARS has constructor : 
`LARS(`
`const arma::mat& data,`
`         const arma::vec& responses,`
`         const bool transposeData = true,`
`          const bool useCholesky = false,`
`          const double lambda1 = 0.0,`
       `const double lambda2 = 0.0,`
       `const double tolerance = 1e-16);`
And training method as : 
`void Train(`
            `const arma::mat& data,`
             `const arma::vec& responses,`
             `arma::vec& beta,`
             `const bool transposeData = true);

Since all the methods are column major (i.e. each input is a column vector) in mlpack, is it a good idea to convert these to column major form too ? 

Also since decision stump and perceptron (though it is less frequently used) have weights as 3rd parameter in the train method, does it sound reasonable to change the above mentioned methods (Train and constructor) to have weights as the third parameter ? (Similar to issue [929](https://github.com/mlpack/mlpack/issues/929) )
(It will be good to have uniform interface across the library and also help in simplifying the cross validation project)

Modified APIs may look like : 
`LinearRegression(`
`const arma::mat& predictors,`
   `                                                       const arma::rowvec& responses,`
` const arma::vec& weights,`
`                                                       const double lambda,`
`                                                       const bool intercept)`

` LinearRegression::Train(`
`const arma::mat& predictors,`
`                                     const arma::rowvec& responses,`
`                                     const arma::rowvec& weights`
`                                     const bool intercept)`

`LARS(`
`const arma::mat& data,`
`         const arma::rowvec& responses,`
`         const bool transposeData = true,`
`          const bool useCholesky = false,`
`          const double lambda1 = 0.0,`
       `const double lambda2 = 0.0,`
       `const double tolerance = 1e-16);`

`void Train(`
            `const arma::mat& data,`
             `const arma::rowvec& responses,`
             `arma::vec& beta,`
             `const bool transposeData = true);`

This will also probably eliminate the `transposeData` variable.

Also `LARS::Predict` will be changed. 
`void Predict(const arma::mat& points,`
           `   arma::vec& predictions,`
`const bool rowMajor = false) const;`

It will look like
`void Predict(const arma::mat& points,`
           `   arma::rowvec& predictions)`
and will have one less variable.

### PR DESCRIPTION
**Pull request by micyril**
Fix #963. Also separate signatures of constructors and Train methods in Linear Regression for learning with weights and without them as discussed in #929.

### CODE REVIEW

File: src/mlpack/methods/linear_regression/linear_regression_main.cpp [hunk 1]
```diff
@@ -140,10 +140,10 @@ int main(int argc, char* argv[])
     {
       // The initial predictors for y, Nx1.
       Timer::Start("load_responses");
-      responses = std::move(CLI::GetParam<vec>("training_responses"));
+      responses = CLI::GetParam<vec>("training_responses").t();
```
Comment (rcurtin) [inline src/mlpack/methods/linear_regression/linear_regression_main.cpp]: We can change the definition of `training_responses` from `PARAM_COL_IN` to `PARAM_ROW_IN`, then the `.t()` isn't necessary.

File: src/mlpack/core/dists/regression_distribution.hpp [hunk 2]
```diff
@@ -49,12 +49,13 @@ class RegressionDistribution
    * @param responses Vector of responses (y).
    */
   RegressionDistribution(const arma::mat& predictors,
-                         const arma::vec& responses) :
-      rf(regression::LinearRegression(predictors, responses))
+                         const arma::vec& responses)
```
Comment (rcurtin) [inline src/mlpack/core/dists/regression_distribution.hpp]: Should we change this to `rowvec` also?
